# Generated by Django 3.2.9 on 2023-06-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitems',
            options={'ordering': ['due_date'], 'verbose_name_plural': 'To do Items'},
        ),
        migrations.AddField(
            model_name='todoitems',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
